/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

import api.PostRequestLogin;
import database.MysqlConnection;
import factory.DAOFactory;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import models.Adresse;
import models.Authentification;
import models.Utilisateur;
import zkfinger.ZKScanner;
import services.PassWordControl;
import services.LoginService;
import api.PostRequestLogin;

/**
 *
 * @author EQIMA
 */
public class AuthentificationJFrame extends javax.swing.JFrame {
PostRequestLogin logs;

    private static AuthentificationJFrame instance;
    
    public static AuthentificationJFrame getInstance(){
        if (instance == null) {
            instance = new AuthentificationJFrame();
        }
        
        return instance;
    } 
       
    /**
System.out.println("");
     * Creates new form AuthentificationJFrame
     */
    public AuthentificationJFrame() {
        initComponents();
        this.setResizable​(true);
        logs=new PostRequestLogin(); 
      //  JOptionPane.showMessageDialog(instance, ZKScanner.getInstance().open(), "Message", JOptionPane.WARNING_MESSAGE);
//            UsbDetected usb=new UsbDetected();
//            usb.start();
    }
    
    private void init(){
    
        
        
    } 
    

    /**
    
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNom_d_utilisateur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbAuthentification = new javax.swing.JButton();
        jpMot_de_passe = new javax.swing.JPasswordField();
        jbSetting = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IDEqima FingerPrint Reader");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Authentification");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nom d'utilisateur :");

        jtNom_d_utilisateur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mot de passe :");

        jbAuthentification.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbAuthentification.setText("S'authentifier");
        jbAuthentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAuthentificationActionPerformed(evt);
            }
        });

        jpMot_de_passe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbSetting.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbSetting.setText("Paramètres");
        jbSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSettingActionPerformed(evt);
            }
        });

        jLabel5.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbAuthentification)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jtNom_d_utilisateur)
                            .addComponent(jpMot_de_passe, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtNom_d_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpMot_de_passe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbAuthentification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSetting)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAuthentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAuthentificationActionPerformed
   //JOptionPane.showMessageDialog(instance, ZKScanner.getInstance().open(), "Message", JOptionPane.WARNING_MESSAGE);
  if (jtNom_d_utilisateur.getText().trim().equals("") || jpMot_de_passe.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(instance, "Tous les champs doivent être remplis ", "Message", JOptionPane.WARNING_MESSAGE);
                
        } else {
            
            if (MysqlConnection.getInstance() == null) {
            JOptionPane.showMessageDialog(instance, "Connectez vous à une base de données", "Message", JOptionPane.WARNING_MESSAGE);          
        
            } else {            

                
                System.out.println(Adresse.getCurrentAdressseMac());
                Adresse adresse = DAOFactory.getAdresseDAO().getbyAdresseMac(Adresse.getCurrentAdressseMac());

                if (adresse == null) {
                    JOptionPane.showMessageDialog(instance, "L'adresse  : "+Adresse.getCurrentAdressseMac()+"  Non Autorisé ", "Message", JOptionPane.WARNING_MESSAGE);  
                } else {
                          
                        LoginService user=PostRequestLogin.Post_One_Login(jtNom_d_utilisateur.getText().trim(), jpMot_de_passe.getText().trim());
                        String resultat_Authentification_server=user.getResultat();

                    if ("false".equals(resultat_Authentification_server)) {
                        JOptionPane.showMessageDialog(instance, "Erreur de l'authentification", "Message", JOptionPane.WARNING_MESSAGE);            
                    } else { 
                        
                        String role=user.getUser().getRole();
                        System.out.println("eto====="+user.getUser().getId());
                        
                         DAOFactory.getUtilisateurDAO().create(new Utilisateur(
                                 user.getUser().getId(),
                                 user.getUser().getNom_d_utilisateur(),
                                 user.getUser().getNom(),
                                 user.getUser().getPrenom(),
                                 user.getUser().getCode_Cms(),
                                 user.getUser().getRole()
                         )); 
                        
                        Date currentDate = new Date();

                        DateFormat shortDateFormat = DateFormat.getDateTimeInstance(
                            DateFormat.SHORT,
                            DateFormat.SHORT);
                        Authentification.getSession().setSession(
                            DAOFactory.getAuthentificationDAO().create(new Authentification(
                                    shortDateFormat.format(currentDate),
                                    Integer.valueOf(user.getUser().getId()),
                                    adresse.getId()
                            ))

                        );

//                        if (utilisateur.getRole().equals(Utilisateur.ADMINISTRATEUR)) {
//                            MenuAdminJFrame.getInstance().showFrame();
//                        } else {
//                            MenuJFrame.getInstance().showFrame();
//                        }
                        MenuJFrame.getInstance().showFrame();
                        ZKScanner.getInstance().demarrer(MenuJFrame.getInstance());
                        AuthentificationJFrame.getInstance().hideFrame();        
                        jtNom_d_utilisateur.setText("");
                        jpMot_de_passe.setText("");
                    }
                }

            }
   
            
        }
    }//GEN-LAST:event_jbAuthentificationActionPerformed

    private void jbSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSettingActionPerformed
        AuthentificationJFrame.getInstance().hideFrame();
        SettingsJFrame.getInstance().showFrame();
    }//GEN-LAST:event_jbSettingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAuthentification;
    private javax.swing.JButton jbSetting;
    private javax.swing.JPasswordField jpMot_de_passe;
    private javax.swing.JTextField jtNom_d_utilisateur;
    // End of variables declaration//GEN-END:variables
    
    public void showFrame(){
        this.setVisible(true);
    }
    
    public void hideFrame(){
        this.setVisible(false);
    }

}
