/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

import factory.DAOFactory;
import javax.swing.JOptionPane;
import models.Adresse;
import models.Utilisateur;

/**
 *
 * @author EQIMA
 */
public class RegistrationJFrame extends javax.swing.JFrame {

    private static RegistrationJFrame instance;
    
    public static RegistrationJFrame getInstance(){
    
        if (instance == null) {
            instance = new RegistrationJFrame();
        }
        
        return instance;
    } 
       
    /**
     * Creates new form AuthentificationJFrame
     */
    public RegistrationJFrame() {
        initComponents();
        this.setResizable​(true);
    }
    
    private void init(){
    
    
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNom_d_utilisateur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbAuthentification = new javax.swing.JButton();
        jpMot_de_passe = new javax.swing.JPasswordField();
        jbRetour = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IDEqima FingerPrint Reader");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Créer un Nouveau Administrateur ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nom d'utilisateur :");

        jtNom_d_utilisateur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mot de passe :");

        jbAuthentification.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbAuthentification.setText("Enregistrer");
        jbAuthentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAuthentificationActionPerformed(evt);
            }
        });

        jpMot_de_passe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbRetour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbRetour.setText("Retour");
        jbRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRetourActionPerformed(evt);
            }
        });

        jLabel5.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbAuthentification)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jtNom_d_utilisateur)
                            .addComponent(jpMot_de_passe, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbRetour)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtNom_d_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpMot_de_passe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAuthentification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRetour)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAuthentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAuthentificationActionPerformed

        if (jtNom_d_utilisateur.getText().trim().equals("") || jpMot_de_passe.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(instance, "Tous les champs doivent être remplis ", "Message", JOptionPane.WARNING_MESSAGE);
                
        } else {
            
            if (Adresse.getCurrentAdressseMac() == null) {
                JOptionPane.showMessageDialog(instance, "Connectez vous à un reseau pour ajouté votre Adresse Mac", "Message", JOptionPane.WARNING_MESSAGE);
            
            } else {
                
               // DAOFactory.getUtilisateurDAO().create(new Utilisateur(jtNom_d_utilisateur.getText().trim(), jpMot_de_passe.getText().trim(), Utilisateur.ADMINISTRATEUR));
                
                DAOFactory.getAdresseDAO().create(new  Adresse(Adresse.getCurrentAdressseMac()));
                
                JOptionPane.showMessageDialog(instance, "L'utlisateur et l'adresse Mac du PC est ajouté dans la base", "Message", JOptionPane.WARNING_MESSAGE);
            
             
                
            }
            
            
                     
            

        }
        
    }//GEN-LAST:event_jbAuthentificationActionPerformed

    private void jbRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRetourActionPerformed

        RegistrationJFrame.getInstance().hideFrame();
        SettingsJFrame.getInstance().showFrame();

    }//GEN-LAST:event_jbRetourActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAuthentification;
    private javax.swing.JButton jbRetour;
    private javax.swing.JPasswordField jpMot_de_passe;
    private javax.swing.JTextField jtNom_d_utilisateur;
    // End of variables declaration//GEN-END:variables

    public void showFrame(){
        this.setVisible(true);
    }
    
    public void hideFrame(){
        this.setVisible(false);
    }

}
